name: ahzab_app
description: "أحزاب الإمام الشاذلي - تطبيق إسلامي"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  google_mobile_ads: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ScheherazadeNew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Bold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
